### ISSUE TITLE
Suggestions and improvements needed for hlsl and compute shader! (also valid for shader code actually)

### ISSUE THREAD

**Issue by nixon-voxell** [amloveyweb/amloveyweb.github.io#10]
For example:
some functions are not linked when using #include.
the syntax highlighting colors are not correct 
  - the one that you noticed the quickest is when you create a void function, the void syntax will turn into white color, looks like the extension don't know what void means

![image](https://user-images.githubusercontent.com/43715558/110414051-1e989f80-80ca-11eb-83f9-9f45388912b0.png)

  - Another issue on syntax highlighting
![image](https://user-images.githubusercontent.com/43715558/110414102-36702380-80ca-11eb-96fd-2b302e487133.png)

Another thing on intellisense is that you should mark them red when a wrong input is fed in, for example in this picture, the input needed is clearly a float3 but a float is given instead, you should make a red underline so that users can see their mistakes easily without going back to unity.
![image](https://user-images.githubusercontent.com/43715558/110414353-aaaac700-80ca-11eb-8aef-260bc55a232c.png)

**Comment by amlovey** [comment]
![](https://user-images.githubusercontent.com/43715558/110414102-36702380-80ca-11eb-96fd-2b302e487133.png) 

@nixon-voxell Why the 'float' show different font style?  May I ask you the name of theme you are using?

**Comment by amlovey** [comment]
Highlighting issues are fixed in my side. Would you mind send the sample files has issue to my mail amlovey@qq.com?

**Comment by nixon-voxell** [comment]
Alright will do.

**Comment by nixon-voxell** [comment]
thank you for all the help, I forgot to close the issue XD.
