### ISSUE TITLE
ShaderLabVSCode: Space is incorrectly removed after `-`

### ISSUE THREAD

**Issue by MattOstgard** [amloveyweb/amloveyweb.github.io#12]
Sometimes a minus sign will incorrectly be treated as negation (left side is expected behaviour, right side is the result after formatting):
![image](https://user-images.githubusercontent.com/6550818/141012728-10c9b89a-7582-4227-a577-e734cd46ebe6.png)

It seems to do it when the minus character is inside parenthesis.

**Comment by amlovey** [comment]
Hi,

This issue is already fixed in my side, the fix will be included in next release. If you need the pre-release package, please send me an email to amlovey@qq.com.

Thanks,
Amlovey

**Comment by amlovey** [comment]
Fixed in v1.3.3
