### ISSUE TITLE
Customize Shortcut Keys

### ISSUE THREAD

**Issue by whitmorekevinj** [amloveyweb/amloveyweb.github.io#2]
For uCodeEditor, it would be nice if the shortcut keys for refresh and save could be customized. If anyone is using Unity's ProBuilder in their project, Ctrl + K is the shortcut for creating a cube primitive in the scene (and cannot be customized). Being able to set the save shortcut to something like Ctrl + Shift + K would help avoid overlap with other assets.

**Comment by amlovey** [comment]
Thank you for reporting this.

In my plan, shortcut customization will be the Key feather in beta version 1.0.5b.

For now, use Commad Palette to execute action is a workaround.

**Comment by amlovey** [comment]
v1.0.5b was submitted to Asset Store.
