### ISSUE TITLE
Maximize Window

### ISSUE THREAD

**Issue by whitmorekevinj** [amloveyweb/amloveyweb.github.io#3]
A couple of small things for those of us with only one monitor and have to rely on maximize window.

When another editor window is placed below the uCodeEditor window, two things happen:
1.) Pressing Shift + Space to maximize uCodeEditor window only works if mouse is over the window tab.
2.) Pressing Shift + Space to maximize leaves a blank space in uCodeEditor window where other window was below.

I'm using Unity 2018.1.3f1 on Windows 10

**Comment by amlovey** [comment]
`Shift + Space` in uCodeEditor does not work on Windows (but does work on macOS) becuase it conflicts with the shortcut in Unity Editor. I have set the shortcut to `Ctrl+Alt+X` to toggle maximize. This change will be include in v1.0.5b. We also can change it later in Shortcuts Customization Window which will be include in v1.0.5b too.

**Comment by amlovey** [comment]
v1.0.5b was submitted to Asset Store.
